#! /bin/sh
### BEGIN INIT INFO
# Provides:          newdjangosite-daily
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the newdjangosite daily FastCGI server
# Description:       starts newdjangosite-daily
### END INIT INFO

NAME=newdjangosite-daily
VIRTUALPYTHON="/var/www/python/newdjangosite-daily/venv/bin/python"
MANAGEFILE="/var/www/python/newdjangosite-daily/web/manage_daily.py"
PIDFILE="/var/fastcgi/newdjangosite-daily.pid"
SOCKFILE="/var/fastcgi/newdjangosite-daily.sock"

start() {
    exec sudo -u www-data $VIRTUALPYTHON $MANAGEFILE runfcgi socket=$SOCKFILE pidfile=$PIDFILE maxrequests=100 maxchildren=4
    return 0
}

stop() {
    if [ -f $PIDFILE ]; then
        kill `cat -- $PIDFILE`
        rm -f -- $PIDFILE
    fi
    return 0
}

case "$1" in
  start)
	echo "Starting $NAME"
	start
	;;
  stop)
	echo "Stopping $NAME"
	stop
	;;
  restart)
	echo "Restarting $NAME"
	stop
	start
	;;
  *)
	echo "Usage: $NAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
